# Generated by Django 3.2.8 on 2022-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('user_limit', models.PositiveIntegerField(default=1)),
                ('max_redemption', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('promo_type', models.CharField(blank=True, choices=[('CART_FIXED', 'Fixed Amount Discount Applied to Cart Total'), ('CART_PERCENTAGE', 'Percentage Discount Applied to Cart Total'), ('PRODUCT_FIXED', 'Fixed Amount Discount Applied to Product Total'), ('PRODUCT_FIXED_PER_ITEM', 'Fixed Amount Discount Applied to Product Per Item'), ('PRODUCT_PERCENTAGE', 'Percentage Discount Applied to Product Total')], max_length=100, null=True)),
                ('discount_value', models.IntegerField()),
                ('minimum_order_amount', models.IntegerField()),
                ('min_order_count', models.IntegerField(default=0)),
                ('max_order_count', models.IntegerField(default=0)),
                ('exclusive_to_user', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('claimable', models.BooleanField(default=True)),
            ],
        ),
    ]
