# Generated by Django 3.2.8 on 2022-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucherredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='promo_users',
            field=models.CharField(choices=[('ANY', 'Anyone'), ('CL', 'Community Leader'), ('SUKI', 'Suki')], default='ANY', max_length=20),
        ),
    ]
