# Generated by Django 3.2.8 on 2022-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, max_length=6, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, max_length=6)),
                ('created_date', models.DateTimeField(auto_now_add=True, max_length=6)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
