# Generated by Django 4.0.5 on 2022-06-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adjustment', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('sellable', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_configs', to='stores.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'product')},
            },
        ),
    ]
