# Generated by Django 3.2.8 on 2022-06-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storeproductconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
