# Generated by Django 3.2.8 on 2022-06-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0, verbose_name='Order Day')),
                ('start_time', models.TimeField(default='00:00:00', verbose_name='From Order Time')),
                ('end_time', models.TimeField(default='23:59:59', verbose_name='To Order Time')),
                ('cutoff_day', models.IntegerField(choices=[(0, 'On the Order Day'), (1, 'Next Monday'), (2, 'Next Tuesday'), (3, 'Next Wednesday'), (4, 'Next Thursday'), (5, 'Next Friday'), (6, 'Next Saturday'), (7, 'Next Sunday')], default=0, verbose_name='Cutoff Day')),
                ('cutoff_time', models.TimeField(default='17:00:00', verbose_name='Cutoff Day')),
                ('delivery_day', models.IntegerField(choices=[(0, 'On the Order Day'), (1, 'Next Monday'), (2, 'Next Tuesday'), (3, 'Next Wednesday'), (4, 'Next Thursday'), (5, 'Next Friday'), (6, 'Next Saturday'), (7, 'Next Sunday')], default=0, verbose_name='Delivery Day')),
            ],
        ),
    ]
