# Generated by Django 3.2.8 on 2022-06-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0007_orderpromo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('self_order_only', models.BooleanField(default=False)),
                ('discount_amount', models.IntegerField()),
                ('minimum_order_amount', models.IntegerField()),
                ('min_order_count', models.IntegerField(default=0)),
                ('max_order_count', models.IntegerField(default=0)),
                ('max_claims', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromoClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stores.order')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_claims', to='promos.promo')),
            ],
        ),
    ]
