# Generated by Django 4.0.4 on 2022-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.FloatField(),
        ),
    ]
