# Generated by Django 3.2.13 on 2022-06-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_invoice_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[('0', 'Not Available'), ('1', 'Pending'), ('2', 'Draft'), ('3', 'Authorised'), ('4', 'Paid'), ('5', 'Partially Paid')], default='1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Expired')], default='0')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='uploader.invoice')),
            ],
        ),
    ]
